server.port=8080
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/plant-ai
jwt.secret=your_jwt_secret_key
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
openai.api.key=AIzaSyA4Mkq-WnnMSxXgcRwJFt2iRr47AwetFBE
ml.service.url=http://localhost:8000/analyze
