server.port=8080
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/plant-ai
jwt.secret=your_jwt_secret_key
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
openai.api.key=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
