server.port=8080
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/plant-ai
jwt.secret=your_jwt_secret_key
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/
groq.model=llama-3.2-11b-vision-preview
ml.service.url=http://localhost:8000/analyze
